version: '3'
services:
 web:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
    - 3000:3000
  depends_on:
    - db
 db:
   image: mongo
   volumes:
    - db-data:/data/db
volumes:
 db-data: {}
                                                                          
